* Imaginary Programming with Emacs
LMs are our best friends in the AI model
menagerie because they make things
intelligible -- by understanding our textual
languages.

Objectives:
- Explain Imaginary Computing
  - AI imagination
  - Discussing AI-generated artwork with an AI
  - Intelligent NFTs
  - Imaginary Web
    - Paracosm vs Metaverse
- Explain Philosophy
  - Simulacra and Science Fiction
  - Truth (epistemology and alethiology)
  - Structuralism: Language based on sign relations
- Demo Imaginary Programming
  - Demonstrate =ilambda.el=

* Resources
- [[http://github.com/semiosis/glossaries-gh/blob/master/imaginary-programming.txt][imaginary programming glossary]]
- [[http://github.com/semiosis/glossaries-gh/blob/master/imaginary-computing.txt][imaginary computing glossary]]
- [[http://github.com/semiosis/glossaries-gh/blob/master/semiosis-protocol.txt][semiosis protocol glossary]]
- [[http://github.com/semiosis/glossaries-gh/blob/master/pen.el.txt][Pen.el glossary]]
- [[https://arxiv.org/abs/2107.13586][https://arxiv.org/abs/2107.13586 Pre-train, Prompt, and Predict]]

* Imaginary Computing
** Language Models is programming for AIs
LMs are our best friends in the AI model
menagerie because they make things
intelligible -- by understanding our textual
languages.

** AI Imagination
- [[https://www.youtube.com/watch?v=d-bvsJWmqlc][Demis Hassabis: creativity and AI]]

** Example: AI Art described by AI
I use AlephAlpha’s multimodal LM to generate
alttext for the eww web browser. This is in
order to keep websites textual.

- https://mullikine.github.io/posts/alephalpha-for-alttext/
- https://mullikine.github.io/posts/describing-melee-s-paintings-with-alephalpha/

** Intelligent NFTs
An =NFT= is like a trading card, or piece of media, and as people.

An =iNTF=, however, also contains a prompt and associated language model, which is intended to interpret the prompt.

- https://alethea.ai/

** A bleak future
- Microsoft
  - [[https://www.marktechpost.com/2021/11/06/microsoft-ai-introduces-turing-bletchley-a-2-5-billion-parameter-universal-image-language-representation-model-t-uilr/][MS models that reify your imagination]]
  - The evil twin on AlephAlpha.
- Facebook / Meta
  - [[https://twitter.com/Meta/status/1456269728687689738?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Etweet][tweet - Enter a world of imagination with Meta]]

** Imaginary Web
 #+BEGIN_SRC text -n :async :results verbatim code
   imaginary internet
   imaginary web
       An imaginary world-wide-web is an
       analog of the World-Wide-Web imagined by a
       language model.
 #+END_SRC

*** Paracosm vs Metaverse
- Paracosm
  - Privacy
  - Personal truth
  - Freedom of imagination
- Metaverse
  - Getting cozy with Mark Zuckerberg's imaginarium, an intellectual prison

* Philosophy
** Simulacra and Science Fiction
Jean Baudrillard speaks about the gap
between the real and the imaginary.

We no longer imagine a world radically
different from the real one, but
rather a world that's a mere expansion
of the real one.

In the postmodern society the gap
between the real and the imaginary
disappears completely, and we are no
longer capable of ideal projections
(of imagining new worlds).
    
We can only imagine mere
reconfigurations of our world, or
simply relive the ideal projections of
past times.

** Truth (epistemology and alethiology)
The Future of Humanity Institute (Oxford)
seems to think this is an important topic.

- [[https://arxiv.org/abs/2110.06674][ 2110.06674  Truthful AI]]
- Datasets are a source of constructivist truth
- Language models are snaphots of society, and a source of several types of truth
  - [[https://www.youtube.com/watch?v=kP-dXK9JEhY][Symbolic Knowledge Distillation]]
- Blockchain is a source of consensus, a type of truth
  - https://mullikine.github.io/posts/language-models-as-truth/

** Structuralism: Language based on sign relations
What do these things have in common:
- Universal Grammar (UG) / Language Acquisition
- C++ template metaprogramming
- GPT-3

Knowledge exists at compile-time (DNA, preprocessor, training).

#+BEGIN_SRC text -n :async :results verbatim code
  structural linguistics
  structuralism
      [#linguistics]
  
      The theoretical position that finds
      meaning in the relation between things,
      rather than in things in isolation.
  
      In other words, it gives primacy to
      pattern over substance.
  
      Example:
          To take a crude example, the colors
          red, green, and amber take on the
          meanings “stop,” “go,” and “caution”
          in relation to each other, in the
          context of a traffic light.
  
          In some other context, and in
          opposition to other colors, red may
          mean something completely different,
          such as socialism or communism, or
          humanity or sacrifice.
  
      Such meanings may be either part of a
      universal pattern or culturally
      determined.
  
      Denotes schools or theories in which
      language is conceived as a self-contained,
      self-regulating semiotic system whose
      elements are defined by their relationship
      to other elements within the system.
#+END_SRC

** Data privacy
The models find useful data from more than just your current file.
- https://mullikine.github.io/posts/imagine-a-project-with-codex/

** Freedom and GPL-3
Problem with language models is they are so large and hidden behind SAAS.

** Solution: Freedom and blockchain
- Language models are ballooning in size like cancer
- Break up the language model into semiotic triadic relation
  - semiotic NFTs
  - Propose a decentralised triadic relations network.
  - https://semiosis.github.io/protocol/
  - http://github.com/semiosis/glossaries-gh/blob/master/semiosis-protocol.txt

* Imaginary Programming
** Methodology
Interactively use the language model to imagine.

** Paradigm
*** Literate programming with =org-mode=
An extension of literate programming.

** Practical application: mocking APIs
** ilambda

* Paracosm Browser
** Pen.el v2
#+BEGIN_SRC text -n :async :results verbatim code
  phenomenology
      The philosophical study of the structures
      of experience and consciousness.
  
      As a philosophical movement it was founded
      in the early years of the 20th century by
      Edmund Husserl and was later expanded upon
      by a circle of his followers at the
      universities of Göttingen and Munich in
      Germany.
  
  firstness
      [#phenomenology]
  
      Something that exists in itself.
  
  secondness
      [#phenomenology]
  
      Must be related to something else.
  
  thirdness
      [#phenomenology]
  
      Requires a more complex relationship than
      secondness, either a relation between
      three things, or a relation between
      relations, or perhaps both at the same
      time.
  
  impure imaginary reality
  second imaginary reality
  third imaginary reality
      This is one's experience of another's
      imagination, whether that be another
      biological mind or a Neural Network.
#+END_SRC

** Definitions
#+BEGIN_SRC text -n :async :results verbatim code
  imaginary reality
  paracosm
      The distinction between this and virtual
      reality is that virtual reality isn't
      really concerned so much with Neural
      Networks for a lazily generated potential
      reality that is constructed as one's own
      mind prompts another.
  
      Also virtual reality is engineered for
      people to explore where imaginary reality
      is generated at will by a user and does
      not follow rules.
  
      Imaginary reality takes place within a
      walled garden of a single mind /
      imagination forming around another.
  
      The interpretation of the output of one
      mind/neural net as have been sensed and
      interpreted by another mind / Neural
      Network, in real time.
  
      Types:
      - pure imaginary reality
      - impure imaginary reality
  
  pure imaginary reality
  first imaginary reality
  daydreaming
      This is one's personal introspective
      experience of their own imagination.
  
  impure imaginary reality
  second imaginary reality
  third imaginary reality
      This is one's experience of another's
      imagination, whether that be another
      biological mind or a Neural Network.
#+END_SRC