* Imaginary Programming with Emacs

Objectives:
- Imaginary Computing
  - Imaginary Programming
  - AI Art
  - Imaginary Web
    - Paracosm vs Metaverse

- Demonstrate 𝑖λ

* Simulacra and Science Fiction
Jean Baudrillard speaks about the gap
between the real and the imaginary.

We no longer imagine a world radically
different from the real one, but
rather a world that's a mere expansion
of the real one.

In the postmodern society the gap
between the real and the imaginary
disappears completely, and we are no
longer capable of ideal projections
(of imagining new worlds).
    
We can only imagine mere
reconfigurations of our world, or
simply relive the ideal projections of
past times.

* Imaginary Web
#+BEGIN_SRC text -n :async :results verbatim code
  imaginary internet
  imaginary web
      An imaginary world-wide-web is an
      analog of the World-Wide-Web imagined by a
      language model.
#+END_SRC

* Language based on signs
#+BEGIN_SRC text -n :async :results verbatim code
  structural linguistics
  structuralism
      [#linguistics]
  
      The theoretical position that finds
      meaning in the relation between things,
      rather than in things in isolation.
      
      In other words, it gives primacy to
      pattern over substance.
      
      Example:
          To take a crude example, the colors
          red, green, and amber take on the
          meanings “stop,” “go,” and “caution”
          in relation to each other, in the
          context of a traffic light.
      
          In some other context, and in
          opposition to other colors, red may
          mean something completely different,
          such as socialism or communism, or
          humanity or sacrifice.
      
      Such meanings may be either part of a
      universal pattern or culturally
      determined.
  
      Denotes schools or theories in which
      language is conceived as a self-contained,
      self-regulating semiotic system whose
      elements are defined by their relationship
      to other elements within the system.
#+END_SRC

* Freedom and GPL-3

* Freedom and blockchain
- Language models are ballooning in size like cancer
- Break up the language model into semiotic triadic relation
  - semiotic NFTs
  - Propose a decentralised triadic relations network.
  - https://semiosis.github.io/protocol/
  - http://github.com/semiosis/glossaries-gh/blob/master/semiosis-protocol.txt

* Imaginary Programming

* Paracosm Browser
** Pen.el v2
#+BEGIN_SRC text -n :async :results verbatim code
  phenomenology
      The philosophical study of the structures
      of experience and consciousness.
  
      As a philosophical movement it was founded
      in the early years of the 20th century by
      Edmund Husserl and was later expanded upon
      by a circle of his followers at the
      universities of Göttingen and Munich in
      Germany.
  
  firstness
      [#phenomenology]
  
      Something that exists in itself.
  
  secondness
      [#phenomenology]
  
      Must be related to something else.
  
  thirdness
      [#phenomenology]
  
      Requires a more complex relationship than
      secondness, either a relation between
      three things, or a relation between
      relations, or perhaps both at the same
      time.
  
  impure imaginary reality
  second imaginary reality
  third imaginary reality
      This is one's experience of another's
      imagination, whether that be another
      biological mind or a Neural Network.
#+END_SRC

** Definitions
#+BEGIN_SRC text -n :async :results verbatim code
  imaginary reality
  paracosm
      The distinction between this and virtual
      reality is that virtual reality isn't
      really concerned so much with Neural
      Networks for a lazily generated potential
      reality that is constructed as one's own
      mind prompts another.
      
      Also virtual reality is engineered for
      people to explore where imaginary reality
      is generated at will by a user and does
      not follow rules.
      
      Imaginary reality takes place within a
      walled garden of a single mind /
      imagination forming around another.
      
      The interpretation of the output of one
      mind/neural net as have been sensed and
      interpreted by another mind / Neural
      Network, in real time.
  
      Types:
      - pure imaginary reality
      - impure imaginary reality
  
  pure imaginary reality
      This is one's personal introspective
      experience of their own imagination.
  
  impure imaginary reality
      This is one's experience of another's
      imagination, whether that be another
      biological mind or a Neural Network.
#+END_SRC